apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  creationTimestamp: null
  name: knative-deployment-civo
spec:
  template:
    metadata:
      creationTimestamp: null
      name: Container Image Name (knative-deployment-civo)-7576266354-1
    spec:
      containerConcurrency: 0
      containers:
        - image: docker.io/kkzonie/Container Image Name (knative-deployment-civo):070aaa1ae49217086c7115f2bf1fba78cd9279d3
          name: user-container
          ports:
            - containerPort: 1337
              protocol: TCP
          readinessProbe:
            successThreshold: 1
            tcpSocket:
              port: 0
          resources: {}
      enableServiceLinks: false
      timeoutSeconds: 300
status: {}
