apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  creationTimestamp: null
  name: knative-deployment-civo
spec:
  template:
    metadata:
      creationTimestamp: null
      name: Container Image Name (knative-deployment-civo)-7575884177-2
    spec:
      containerConcurrency: 0
      containers:
        - image: docker.io/kkzonie/Container Image Name (knative-deployment-civo):8ad36926da2ae0b07b02eaa21f7f4d442873d91d
          name: user-container
          ports:
            - containerPort: 1337
              protocol: TCP
          readinessProbe:
            successThreshold: 1
            tcpSocket:
              port: 0
          resources: {}
      enableServiceLinks: false
      timeoutSeconds: 300
status: {}
